[profile.default]
src = "src"
out = "out"
script = "script"
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
evm_version = "shanghai"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
solc = "0.8.25"
allow_paths = ["node_modules"]
libs = ["node_modules", "lib"]



[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true




# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
